# Nexus Protocol - Kustomization
# Deploy all resources: kubectl apply -k infrastructure/kubernetes/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-protocol

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: nexus-protocol
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/colemanwhaylon/nexus-protocol/api
    newTag: latest
